config/routes.rb
Rails.application.routes.draw do

  resources :tenant do
    resources :projects
  end
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => { 
    :registrations => "milia/registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords", 
  }

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :tenant
  
  validates_uniqueness_of :title

    validate :free_plan_can_only_have_one_project

    def free_plan_can_only_have_one_project

        if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == 'free')
            errors.add(:base, "Free plans cannot have more than one project")
        end
    end
    
    def self.by_plan_and_tenant(tenant_id)

        tenant = Tenant.find(tenant_id)

        if tenant.plan == 'premium'
            tenant.projects
        else
            tenant.projects.order(:id).limit(1)
        end

    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_tenant, only: [:show, :edit, :update, :destroy, :new, :create]
  before_action :verify_tenant

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_url, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_completion_date, :tenant_id)
    end
    
    def set_tenant
      @tenant = Tenant.find(params[:tenant_id])

    end

    def verify_tenant

      unless params[:tenant_id] == Tenant.current_tenant_id.to_s
        redirect_to :root,
          flash: { error: 'You are not authorized to access any organization other than your own'}
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [@tenant, @project], :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :details, :class => 'form-control' %>
    </div>
    <%=f.error_span(:details) %>
  </div>
  <div class="form-group">
    <%= f.label :expected_completion_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :expected_completion_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:expected_completion_date) %>
  </div>
  
  <br/>
  <%= f.hidden_field :tenant_id, value: params[:tenant_id], :class => 'form-control' %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/_list.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:expected_completion_date) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, 
                tenant_project_path(project, tenant_id: @tenant.id, class: 'main-linl') %></td>
        <td><%= project.details %></td>
        <td><%= project.expected_completion_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tenantproject_path(project, tenant_id: @tenant.id), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tenant_project_path(project, tenant_id: @tenant.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm",
                                 :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_tenant_project_path(tenant_id: @tenant.id),
            :class => 'btn btn-primary' %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @project.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @project.details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expected_completion_date) %>:</strong></dt>
  <dd><%= @project.expected_completion_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tenant_id) %>:</strong></dt>
  <dd><%= @project.tenant_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>